title: 'Finique Studio -  дизайн интерьеров, архитектурные решения'
default_lang: ru
author:
  name: Игорь
  email: finique@outlook.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Дизайн интерьеров квартир и коттеджей, архитектура коттеджей. Разработка архитектурного и дизайн проектов.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
