title: 'FINIQUE STUDIO'
default_lang: ru
author:
  name: S.O.D
  email: sod.inform@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Дизайн интерьера в Киеве, архитектурный проект. Заказать проект дизайна интерьера коттеджа, квартиры или офиса, архитектурный проект дома по тел. 096 77 45 002.   Профессиональный подход к проектированию'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
